spring.application.name=Virtual-lab-app
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://vidvan:Viddu258@cluster0.lelipi7.mongodb.net/virtual_coding_lab?appName=Cluster0}

spring.data.mongodb.auto-index-creation=true

server.port=${PORT:8080}
jwt.secret=${JWT_SECRET:veryveryveryverysecuresecretkey123}
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository=DEBUG