spring.application.name=Virtual-lab-app
spring.data.mongodb.uri=mongodb://localhost:27017

spring.data.mongodb.auto-index-creation=true

server.port=${PORT:8080}
jwt.secret=${JWT_SECRET:veryveryveryverysecuresecretkey123}
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository=DEBUG
